spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/csee/CSES.git
          username: DalecBot
          password: abot2018
          search-paths: config-repo

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}
