server:
  port: 11000


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cses_usermanager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


druid:
  url: jdbc:mysql://127.0.0.1:3306/cses_usermanager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: 123456
  driver-class: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: cn.edu.nju.software.usermanager.domain.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: cn.edu.nju.software.usermanager.dao.mapper
  not-empty: true
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000